version: '3.8'

secrets:
  cloudflare-token:
    file: "./secrets/cloudflare-token.secret"
  cloudflare-email:
    file: "./secrets/cloudflare-email.secret"

services:
  traefik:
    image: traefik:v2.9
    ports:
      - 443:443
      - 80:80
    command:
      - "--configFile=/etc/traefik/config.yml"
    labels:
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/traefik/config.yml:/etc/traefik/config.yml
      - ./configs/traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./.htpasswd:/shared/.htpasswd:ro
    secrets:
      - "cloudflare-token"
      - "cloudflare-email"
    environment:
      - "CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare-token"
      - "CF_API_EMAIL_FILE=/run/secrets/cloudflare-email"
    networks:
      - web
      - tracing

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "4318:4318"
      - "16686:16686"
    labels:
      - "traefik.enable=true"
    networks:
      - web
      - tracing

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
    networks:
      - web
      
networks:
  web:
    external: true
  tracing:
    external: true
